trade:
  ticker: "KRW-BTC"          # 거래 코인
  seed_krw: 1000000          # 모의거래 시드
  parts: 20                  # 분할 횟수 (1/20)
  drop_pct: 0.01             # 평단 대비 하락 추가매수(1%)
  rise_pct: 0.03             # 평단 대비 상승 전량매도(3%)
  min_order_krw: 5000        # 업비트 최소 주문액
  cooldown_sec: 10.0         # 주문 후 쿨다운(초)
  max_buys_per_hour: 5       # 1시간 내 최대 매수 횟수
  poll_sec: 1.0              # 내부 루프 주기(초) — 로그 빈도는 log_every_sec로 제어
  log_every_sec: 3600.0      # 5초마다 상태 로그 1회
  cron_log: "0 0 * * * *"    # 상태 로그 (매 시간)
  paper_trade: true          # true=모의, false=실거래
  log_dir: "logs"            # 로그 폴더 (기본 /logs)
  ws_stale_fallback_sec: 3.0 # WS 수신 정지 시 REST로 대체 허용 지연(초)

fear_greed:
  enabled: true             # 사용 여부
  run_in_modes: ["basic"]    # 카카오톡 1회 전송할 모드 선택
  mode: "daily"             # "daily" | "interval"
  daily_kst_hour: 9         # 한국시간 매일 9시
  interval_sec: 3600        # 조회 주기(초) - 1시간 = 3600
  notify_kakao: true        # 카카오톡 알림 설정
  notify_on_start: true     # 시작 즉시 1회 알림을 보낼지
  log_file: "fg_index.log"  # 로그 파일명 (trade.log_dir 폴더 안에 생성)

notify:
  # 우선순위 지정 (옵션): discord | kakao | both
  use: "discord"
  discord:
    enabled: true
    username: "CoinTrade Bot"     # 선택
    avatar_url: ""                # 선택 (이미지 URL)
    webhooks:
      basic: "https://discord.com/api/webhooks/1430091791960641571/66XSym0-6ftoMdc9x9EvVA3JUsvzmOZAJyJaa3rBKmbHcgFnoUl9dnKiDL0pUH2fTAmZ"
      volatility: "https://discord.com/api/webhooks/1430091200517636217/oEBsYJcpmVUNKpkVtKxuOVFK5Ka-O5hFLKHY46l_IvqGVfT7RZQtiQZyZDQu_EuL3BFX"
      volume: "https://discord.com/api/webhooks/1430090910477320192/MdRqoOlNFzPFv9gg3HsJU5KRv4G1syl6b3NwHitihZH-DS7vX3UCKuXjfeyqkam5HEPk"
      rsi: "https://discord.com/api/webhooks/1430089548066586685/X-YyYDZB4KP-RSo8d8Y-L8UiaOzgBpWFE9PYHiOI6e1sBsPAJZEnF-Rty45FShONR3vs"
      rsi_trend: "https://discord.com/api/webhooks/1430463255255453878/REsez91FdDXeG4BvH8qrMl1vdbAaNr0eUVC1u-zYP31krTXvF1iXaeT7uHYAT8Nmm1Y2"
    default_webhook: ""           # (선택) 모드별 URL이 없을 때 사용할 기본 훅
  kakao:
    enabled: false  # 카카오를 백업/대체로 쓰려면 true

upbit:
  rest_cooldown_sec: 600   # REST 호출 실패 시 다음 시도까지 대기 시간(초)

## 변동성 기반
volatility:
  enabled: true
  window_sec: 300             # 최근 5분 간격으로 변동성 계산
  ref_vol_pct: 0.5            # 기준 변동성(%) - 이 값과 비교해 스케일링
  min_scale: 0.5              # 트리거 축소 하한 (너무 민감하지 않게)
  max_scale: 2.0              # 트리거 확대 상한 (무한정 커지지 않게)

## 거래량 급증 필터
volume_spike:
  enabled: true
  tf: "minute"                # 'minute' 고정(1분봉)
  lookback: 20                # 과거 20봉 평균 대비
  spike_multiplier: 3.0       # 평균의 3배 이상이면 급증으로 판단
  cooldown_sec: 300           # 감지 시 매수 5분 중단

## RSI 필터
rsi:
  enabled: true
  period: 14                  # RSI 기간
  buy_below: 30.0             # RSI가 이 값 미만일 때만 추가매수 허용
  use_close_1m: true          # 1분봉 증가 기준으로 계산(ws price로 같이 계산도 가능)

rsi_trend:
  enabled: true               
  rsi_period: 14              # RSI 기간
  rsi_buy: 45                 # 매수 고려 RSI 이하
  rsi_sell: 65                # 익절 고려 RSI 이상
  ema_short: 7                # 단기 EMA
  ema_long: 20                # 장기 EMA
  rebound_lookback: 10        # 최근 N틱 내 EMA_short 아래였는지 탐지
  use_init_seed_ohlcv: true   # 시작 시 1분봉으로 EMA/RSI 시드
  unit_weights: [1, 1, 1.5, 1.5, 2, 2, 2.5, 3]   # 가중 분할 (합=13 → 시드 * (가중/13) 만큼 단계별 매수)
  drop_ladder_pct:          # 단계형 드랍 트리거(평단 대비 하락폭) — 단계가 올라갈수록 더 깊은 하락에서만 추가매수
    - 0.005  # -0.5%
    - 0.010  # -1.0%
    - 0.017  # -1.7%
    - 0.025  # -2.5%
    - 0.035  # -3.5%
    - 0.046  # -4.6%
    - 0.058  # -5.8%
    - 0.071  # -7.1%
  parts: 6                    # rsi_trend 전용 분할 수
  drop_pct: 0.008             # rsi_trend 전용 드랍 오버라이드
  rise_pct: 0.015             # rsi_trend 전용 라이즈 오버라이드